#!/usr/bin/env bash

# Update the package list and install Apache if not already installed
apt-get update
apt-get install -y apache2

# Create an index.html file with "Hello Holberton" content
echo "Hello Holberton" > /var/www/html/index.html

# Start the Apache service
service apache2 start

